package:
  name: stopeight-clibs
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: https://github.com/specpose/stopeight-clibs.git

requirements:
  build:
    - cmake
    - qt >=5.6.0

about:
  summary: Comparing sequences of points in 2 dimensions.
  license_file: LICENSE
