name: "Example 2: Other shells"

on:
  push:
    branches:
    - 'actions-conda'
  pull_request:
    branches:
    - 'actions-conda'

jobs:
  example-2-linux:
    name: Ex2 Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: conda-build-env
          environment-file: etc/conda-build-environment.yml
      - name: Bash
        shell: bash -l {0}
        run: |
          conda build .

  example-2-mac:
    name: Ex2 Mac
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: conda-build-env
          environment-file: etc/conda-build-environment.yml
      - name: Sh
        shell: sh -l {0}
        run: |
          conda build .

  example-2-win:
    name: Ex2 Windows
    runs-on: 'windows-latest'
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: foo
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Sh
        shell: sh -l {0}
        run: |
          conda info
          conda list
      - name: PowerShell
        shell: powershell
        run: |
          conda info
          conda list
      - name: PowerShell Core
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Cmd.exe
        shell: cmd /C CALL {0}
        run: >-
          conda info &&
          conda list
